name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  test_01sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run 01sh script
        run: ./01.sh


